### ISSUE TITLE
Doesn't work for matrix sizes which are not powers of 2

### ISSUE THREAD

**Issue by visva89** [KingJamesSong/BatchED#2]
BatchED.utils_ed_plus.Batched_ED_Plus.apply just gives an error... Generally, its quite hard to find a use for such a code.

```
[utils_ed_plus.py:217](https://file+.vscode-resource.vscode-cdn.net/mnt/hd1/Dropbox/tmp/projects/SNIPPETS/torch_eigs/BatchED/utils_ed_plus.py:217), in DivideStep(x_orig)
    [215](file:///mnt/hd1/Dropbox/tmp/projects/SNIPPETS/torch_eigs/BatchED/utils_ed_plus.py?line=214) t1 = x[:, :half_size, :half_size]
    [216](file:///mnt/hd1/Dropbox/tmp/projects/SNIPPETS/torch_eigs/BatchED/utils_ed_plus.py?line=215) t2 = x[:, half_size:, half_size:]
--> [217](file:///mnt/hd1/Dropbox/tmp/projects/SNIPPETS/torch_eigs/BatchED/utils_ed_plus.py?line=216) return torch.cat([t1,t2],dim=0), xnorm, beta

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 4 but got size 5 for tensor number 1 in the list.
```

**Comment by KingJamesSong** [comment]
Hi,

  Thanks for your question.

  I did this extension in my free time just for interst. It is designed just for matrices of size of powers of 2. 
  
  If you would like to apply to other sizes, you could change the code [here](https://github.com/KingJamesSong/BatchED/blob/main/utils_ed_plus.py#L71) to customize the divide step.

  Also if your dimension is smaller than 32, I would suggest the batched_ED solver.
